name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: packages/mcp

      - name: Build
        run: yarn build && yarn clean
        working-directory: packages/mcp

      - name: Lint
        run: yarn lint
        working-directory: packages/mcp

      - name: Prettier
        run: yarn prettier:check
        working-directory: packages/mcp
